### ISSUE TITLE
Page Ideas

### ISSUE THREAD

**Issue by rhovey15** [rhovey15/iowa_site#1]
Come up with four ideas for pages.

**Comment by rhovey15** [comment]
My pages will be:
Swenson BBQ
Giant rock
Giant Lego statue 
Historical intersection (at which two generals said sup)

**Comment by Wicksey1818** [comment]
I will be doing my pages over:
Field of Dreams (Film Site)
Principal Park
A local trout fish hatchery in Decorah
National Mississippi River Museum

**Comment by jgdeaton** [comment]
Simpson College
The field (random field)
my apartment building (secretly the birth-site of the movie brave heart)
wildlife wax museum(stuffed animals at bass pro)
